# -*- coding: utf-8 -*-
"""Olá, este é o Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

print('Hello World')
'''nome = input('digite o nome:')'''
"""print(nome)"""
#type(nome)#

"""A função eval() recebe uma string, mas trata como um valor numérico"""
peso = eval(input('digite seu peso: '))
alt = eval(input('digite sua altura: '))

imc = peso/(alt**2)

print('IMC:',imc)